version: '3.9'

services:
  postgres:
    image: 'docker.io/postgres:17-alpine3.20'
    restart: unless-stopped
    shm_size: 128mb
    env_file: postgres.env

  mailpit:
    image: 'docker.io/axllent/mailpit'
    restart: unless-stopped
    ports:
      - '8025:8025'
      - '1025:1025'