version: '3.9'

services:
  postgres:
    image: 'docker.io/postgres:17'
    restart: unless-stopped
    env_file: postgres.env
    ports:
      - '5432:5432'

  mailpit:
    image: 'docker.io/axllent/mailpit'
    restart: unless-stopped
    ports:
      - '8025:8025'
      - '1025:1025'