version: '3.9'

services:
  postgres:
    image: 'docker.io/postgres:17'
    restart: unless-stopped
    env_file: postgres.env
    ports:
      - '127.0.0.1:5432:5432'

  mailpit:
    image: 'docker.io/axllent/mailpit'
    restart: unless-stopped
    ports:
      - '127.0.0.1:8025:8025'
      - '127.0.0.1:1025:1025'